models/User.php
<?php
namespace app\models;

use app\base\DateFormatter;
use Yii;
use yii\base\InvalidArgumentException;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\helpers\VarDumper;

/**
 * This is the model class for table "{{%user}}".
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $status
 * @property string $last_login_at
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 *
 * @property-read array $formattedCreatedAt see {@link User::getFormattedCreatedAt()} for more info
 * @property-read array $formattedUpdatedAt see {@link User::getFormattedUpdatedAt()} for more info
 * @property-read array $statuses see {@link User::getStatuses()} for more info
 * @property-read string $statusTitle see {@link User::getStatusTitle()} for more info
 * @property-read bool $hasIsAdminStatus see {@link User::getHasIsAdminStatus()} for more info
 *
 * @property User $createdBy
 * @property User $updatedBy
 *
 * @author Edgars Naglis <edgarsnaglis300@gmail.com>
 *
 * @copyright 2020 SIA "Web Multishop Company"
 *
 * @package app\models\User
 */
class User extends ActiveRecord
{
    const STATUS_IS_ADMIN = 1;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['username', 'required'],
            ['password', 'passwordHashShouldBeSetValidator', 'on' => 'create'],
            ['username', 'string', 'max' => 100],
            ['username', 'filter', 'filter' => 'trim'],
            ['username', 'string'],
            ['username', 'unique', 'message' => Yii::t('app.models.User', 'This username has already been taken.')],
            [['password_hash'], 'string', 'max' => 100],
            ['status', 'default', 'value' => self::STATUS_IS_ADMIN],
            ['status', 'in', 'range' => [self::STATUS_IS_ADMIN]],
            ['password', 'safe'],
        ];
    }

    /**
     * @param $attribute
     */
    public function passwordHashShouldBeSetValidator($attribute)
    {
        if (is_null($this->password_hash)) {
            $this->addError($attribute, Yii::t('yii', '{attribute} cannot be blank.', ['attribute' => $attribute]));
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'            => Yii::t('app.models.User', 'User ID'),
            'username'      => Yii::t('app.models.User', 'Username'),
            'password_hash' => Yii::t('app.models.User', 'Password hash'),
            'status'        => Yii::t('app.models.User', 'Status'),
            'password'      => Yii::t('app.models.User', 'Password'),
            'last_login_at' => Yii::t('app.models.User', 'Last login at'),
            'created_at'    => Yii::t('app', 'Created at'),
            'created_by'    => Yii::t('app', 'Creator user ID'),
            'updated_at'    => Yii::t('app', 'Updated at'),
            'updated_by'    => Yii::t('app', 'Updater user ID'),
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::class, ['id' => 'created_by']);
    }

    /**
     * @return ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(User::class, ['id' => 'updated_by']);
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'Blameable' => [
                'class' => BlameableBehavior::class,
            ],
            'Timestamp' => [
                'class' => TimestampBehavior::class,
                'value' => new Expression('UTC_TIMESTAMP()'),
            ]
        ];
    }

    /**
     * @param string $password
     *
     * @return string
     */
    public static function generatePasswordHash(string $password)
    {
        return Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Changes password to new one
     *
     * @param string $password
     *
     * @param bool $saveAfterwards
     *
     * @return bool
     */
    public function setPassword(string $password, $saveAfterwards = false)
    {
        Yii::info('User ' . $this->id . ' password changed');
        $this->password_hash = self::generatePasswordHash($password);
        $this->password = '';
        if ($saveAfterwards) {
            return $this->save(false, ['password']);
        }

        return true;
    }

    /**
     * @return string
     */
    public function getPassword()
    {
        return '';
    }

    /**
     * @param string $password
     *
     * @return bool
     */
    public function validatePassword(string $password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Returns possible values of "status" attribute along with value titles
     *
     * @return array
     */
    public static function getStatuses()
    {
        return [
            static::STATUS_IS_ADMIN => Yii::t('app.models.User', 'Is admin')
        ];
    }

    /**
     * Returns current "status" attribute value title
     *
     * @return string|null
     */
    public function getStatusTitle()
    {
        $statuses = $this->getStatuses();

        return (isset($statuses[$this->status]) ? $statuses[$this->status] : null);
    }

    /**
     * Returns "created at" value as formatted date string or as an DateTime object
     *
     * @param string|null $format
     *
     * @return string|\DateTime If format is null, DateTime object is returned.
     * @link http://php.net/manual/en/datetime.format.php
     */
    public function getFormattedCreatedAt($format = 'c')
    {
        return DateFormatter::formatUtcDate($this->created_at, $format);
    }

    /**
     * Returns "updated at" value as formatted date string or as an DateTime object
     *
     * @param string|null $format
     *
     * @return string|\DateTime If format is null, DateTime object is returned.
     * @link http://php.net/manual/en/datetime.format.php
     */
    public function getFormattedUpdatedAt($format = 'c')
    {
        return DateFormatter::formatUtcDate($this->updated_at, $format);
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->username;
    }

    /**
     * @param string $username
     *
     * @return null|User
     */
    public static function findByUsername($username)
    {
        return self::findOne(['username' => $username]);
    }

    /**
     * @return bool
     */
    public function getHasIsAdminStatus()
    {
        return ($this->status == self::STATUS_IS_ADMIN);
    }

    /**
     * @param $status
     *
     * @return int
     */
    public static function countUsersWithStatus($status)
    {
        $statuses = self::getStatuses();
        if (isset($statuses[$status])) {
            return User::find()->where(['status' => $status])->count();
        } else {
            Yii::error('Unknown status: ' . VarDumper::dumpAsString($status));
            throw new InvalidArgumentException('Unknown status');
        }
    }

    /**
     * @param $id
     *
     * @return mixed|string
     */
    public static function usernameById($id)
    {
        $username = self::find()
            ->where(['id' => $id])
            ->select(['username'])
            ->asArray()
            ->column();
        $username = (isset($username[0]) ? $username[0] : null);

        return $username;
    }
}

controllers/UsersController.php
<?php
namespace app\controllers;

use Yii;
use app\models\User;
use app\models\search\User as UserSearch;
use app\base\Controller;
use yii\helpers\Url;
use yii\web\ConflictHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

/**
 * UsersController implements the CRUD actions for {@link User} model.
 *
 * @author Edgars Naglis <edgarsnaglis300@gmail.com>
 *
 * @copyright 2020 SIA "Web Multishop Company"
 *
 * @package app\models\User
 */
class UsersController extends Controller
{

    public $layout = 'admin';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only'  => ['index', 'view', 'create', 'update', 'delete'],
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],
                        'allow'   => true,
                        'roles'   => ['@'],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public static function getIcon()
    {
        return '<i class="fa fa-users"></i>';
    }

    /**
     * Lists all User models.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $searchModel->scenario = 'search';
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $this->heading = Yii::t('app.models.User', 'Users');
        $this->view->title = $this->heading . ' | ' . Yii::$app->name;
        $this->view->params['breadcrumbs'][] = $this->getIcon() . ' ' . $this->heading;

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function addParentBreadcrumbs()
    {
        $this->view->params['breadcrumbs'][] = [
            'label' => $this->getIcon() . ' ' . Yii::t('app.models.User', 'Users'),
            'url'   => ['index'],
        ];
    }

    /**
     * Displays a single User model.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $this->heading = $model->id . '. &quot;' . $model->title . '&quot;';
        $this->subHeading = Yii::t('app.models.User', 'User');
        $this->view->title = $this->subHeading . ' ' . $this->heading . ' | ' . Yii::$app->name;
        $this->addParentBreadcrumbs();
        $this->view->params['breadcrumbs'][] = $this->heading;

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        $model->scenario = 'create';

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $mode = Yii::$app->request->post('mode', 'save');
            if ($mode == 'save-and-create-new') {
                Yii::$app->session->addFlash(
                    'success',
                    Yii::t('app', 'New <a href="{url}">{modelClass}</a> successfully created', [
                        'modelClass' => Yii::t('app.models.User', 'User'),
                        'url'        => Url::to(['view', 'id' => $model->id])
                    ])
                );

                return $this->redirect(['create']);
            } else {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
            $this->heading = Yii::t('app', 'Create new {modelClass}', [
                'modelClass' => Yii::t('app.models.User', 'User'),
            ]);
            $this->view->title = $this->heading . ' | ' . Yii::$app->name;
            $this->addParentBreadcrumbs();
            $this->view->params['breadcrumbs'][] = Yii::t('app', 'Create new');

            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $mode = Yii::$app->request->post('mode', 'save');
            if ($mode == 'save-and-create-new') {
                Yii::$app->session->addFlash(
                    'success',
                    Yii::t('app', 'Save successfull')
                );

                return $this->redirect(['create']);
            } else {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $this->heading = Yii::t('app', '{id}. &quot;{title}&quot;', [
                'id'    => $model->id,
                'title' => $model->title
            ]);
            $this->subHeading = Yii::t('app.models.User', 'User');
            $this->view->title = Yii::t('app', 'Updating {modelClass} {id}. {title} | {appName}', [
                'modelClass' => $this->subHeading,
                'id'         => $model->id,
                'title'      => $model->title,
                'appName'    => Yii::$app->name,
            ]);
            $this->addParentBreadcrumbs();
            $this->view->params['breadcrumbs'][] = [
                'label' => $model->id . '. &quot;' . $model->title . '&quot;',
                'url'   => ['view', 'id' => $model->id],
            ];
            $this->view->params['breadcrumbs'][] = Yii::t('app', 'Update');

            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param integer $id
     *
     * @return mixed
     * @throws ConflictHttpException
     * @throws NotFoundHttpException
     * @throws \Exception
     */
    public function actionDelete($id)
    {
        $user = $this->findModel($id);

        // Do not let delete last admin user
        if ($user->hasIsAdminStatus && User::countUsersWithStatus(User::STATUS_IS_ADMIN) == 1) {
            Yii::$app->session->addFlash(
                'warning',
                Yii::t(
                    'app.models.User',
                    'To avoid lockout out of admin interface, last admin user ({username}) deletion was interrupted',
                    [
                        'username' => $user->username
                    ]
                )
            );

            return $this->redirect($_SERVER['HTTP_REFERER']);
        }

        // Do not let delete yourself
        elseif ($user->id == Yii::$app->user->id) {
            Yii::$app->session->addFlash(
                'warning',
                Yii::t(
                    'app.models.User',
                    'To avoid lockout out of admin interface, deletion of your own user account ({username}) was interrupted'
                )
            );

            return $this->redirect($_SERVER['HTTP_REFERER']);
        }
        $user->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id
     *
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested User does not exist.');
        }
    }
}

views/users/_form.php
<?php

use app\models\User;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/**
 * Form create/update form view
 *
 * @var yii\web\View $this
 * @var app\models\User $model
 */
?><div class="admin-data-form user-form">

    <?php $form = ActiveForm::begin(); ?>
    <header class="admin-data-form__header row">
        <?php if ($model->isNewRecord) { ?>
            <div class="col-md-offset-6 col-md-1">
                <?= Html::a(
                    Yii::t('app', 'Cancel'),
                    ['index'],
                    ['class' => 'btn btn-md btn-block btn-default']
                ) ?>
            </div>
            <div class="col-md-3">
                <?= Html::submitButton(
                    '<span class="glyphicon glyphicon-floppy-disk"></span> ' . Yii::t('app', 'Save & create new'),
                    [
                        'class' => 'btn btn-md btn-block btn-info',
                        'name' => 'mode',
                        'value' => 'save-and-create-new'
                    ]
                ) ?>
            </div>
            <div class="col-md-2">
                <?= Html::submitButton(
                    '<span class="glyphicon glyphicon-floppy-disk"></span> ' . Yii::t('app', 'Save'),
                    ['class' => 'btn btn-md btn-block btn-success']
                ) ?>
            </div>
        <?php } else { ?>
            <div class="col-md-2">
                <?= Html::a(
                    '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'Create new'),
                    ['create'],
                    ['class' => 'btn btn-md btn-block btn-success']
                ) ?>
            </div>
            <div class="col-md-offset-3 col-md-1">
                <?= Html::a(
                    Yii::t('app', 'Delete'),
                    ['delete', 'id' => $model->id],
                    [
                        'class' => 'btn btn-link',
                        'data' => [
                            'confirm' => Yii::t('app', 'Are you sure you want to delete this {modelClass}?', [
                                'modelClass' => Yii::t('app.models.User', 'User'),
                            ]),
                            'method' => 'post',
                        ],
                    ]
                ) ?>
            </div>
            <div class="col-md-1">
                <?= Html::a(
                    Yii::t('app', 'Cancel'),
                    ['index'],
                    ['class' => 'btn btn-md btn-block btn-default']
                ) ?>
            </div>
            <div class="col-md-3">
                <?= Html::submitButton(
                    '<span class="glyphicon glyphicon-floppy-disk"></span> ' . Yii::t('app', 'Save & create new'),
                    [
                        'class' => 'btn btn-md btn-block btn-info',
                        'name' => 'mode',
                        'value' => 'save-and-create-new'
                    ]
                ) ?>
            </div>
            <div class="col-md-2">
                <?= Html::submitButton(
                    '<span class="glyphicon glyphicon-floppy-disk"></span> ' . Yii::t('app', 'Save'),
                    ['class' => 'btn btn-md btn-block btn-primary']
                ) ?>
            </div>
        <?php } ?>
    </header>
    <div class="row">
        <div class="col-sm-offset-2 col-sm-6">
            <div class="form-horizontal">
                <?= $form->field(
                    $model,
                    'username',
                    [
                        'labelOptions' => ['class' => 'col-sm-6 control-label'],
                        'template' => "{label}<div class=\"col-sm-6\">{input}\n{hint}\n{error}</div>"
                    ]
                )->textInput(
                    [
                        'maxlength' => true,
                        'class' => 'form-control',
                        'placeholder' => Yii::t('app', 'email.address@example.com'),
                    ]
                ) ?>
                <?= $form->field(
                    $model,
                    'password',
                    [
                        'labelOptions' => ['class' => 'col-sm-6 control-label'],
                        'template' => "{label}<div class=\"col-sm-6\">{input}\n{hint}\n{error}</div>"
                    ]
                )->passwordInput(
                    [
                        'maxlength' => true,
                        'class' => 'form-control',
                    ]
                ) ?>
                <?= $form->field(
                    $model,
                    'status',
                    [
                        'labelOptions' => ['class' => 'col-sm-6 control-label'],
                        'template' => "{label}<div class=\"col-sm-6\">{input}\n{hint}\n{error}</div>"
                    ]
                )->dropDownList(
                    $model->statuses,
                    [
                        'class'=>'form-control'
                    ]
                ) ?>
            </div>
        </div>
    </div>
    <footer class="admin-data-form__footer">
    <?php if (!$model->isNewRecord): ?>
        <span class="entry__created"><?= Yii::t('app', 'Created') ?>: <span class="created-by"><?= User::usernameById($model->created_by) ?></span> (<span class="created-at"><?= $model->formattedCreatedAt ?></span>)</span>
        <?php if ($model->updated_at): ?>
        <span class="entry__updated"><?= Yii::t('app', 'Updated') ?>: <span class="updated-by"><?= User::usernameById($model->updated_by) ?></span> (<span class="updated-at"><?= $model->formattedUpdatedAt ?></span>)</span>
        <?php endif; ?>
    <?php endif; ?>
    </footer>
    <?php ActiveForm::end(); ?>

</div>

views/users/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password_hash') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app.models.User', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app.models.User', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/users/create.php
<?php

/**
 * Users creation view
 *
 * @var yii\web\View $this
 * @var app\models\User $model
 */
?><div class="admin-page admin-page_data-create user-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/users/index.php
<?php

use app\models\User;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\widgets\Pjax;

/**
 * Users list view
 *
 * @var yii\web\View $this
 * @var app\models\search\User $searchModel
 * @var yii\data\ActiveDataProvider $dataProvider
 */
?><div class="admin-page admin-page_data-index user-index">
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <div class="row">
        <div class="col-sm-4 col-sm-offset-8 col-md-2 col-md-offset-10"><?=  Html::a(
                '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'Create new'),
                ['create'],
                [
                    'class' => 'btn btn-success btn-block btn-sm',
                    'style' => 'margin-bottom: 10px;'
                ]
            )
            ?></div>
    </div>
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'attribute' => 'id',
                'headerOptions' => ['class' => 'col_id'],
                'contentOptions' => ['class' => 'col_id'],
            ],
            [
                'attribute' => 'username',
                'headerOptions' => ['class' => 'col_username'],
                'contentOptions' => ['class' => 'col_username'],
                'format' => 'html',
                'value' => function($searchModel) {

                    /**
                     * @var app\models\search\User $searchModel
                     */
                    return '<a title="' . Yii::t('yii', 'View') . '" href="' .
                        Url::to(['users/view', 'id' => $searchModel->id]) .
                    '">' . $searchModel->username . '</a>';
                },
            ],
            [
                'attribute' => 'status',
                'headerOptions' => ['class' => 'col_status'],
                'contentOptions' => ['class' => 'col_status'],
                'filter' => Html::activeDropDownList(
                    $searchModel,
                    'status',
                    ArrayHelper::merge(
                        [
                            0 => Yii::t('app', 'Any')
                        ],
                        $searchModel->statuses
                    ),
                    ['class'=>'form-control']
                ),
                'value' => function($searchModel) {

                    /**
                     * @var app\models\search\User $searchModel
                     */
                    return $searchModel->statusTitle;
                },
            ],
            [
                'attribute' => 'updated_at',
                'headerOptions' => ['class' => 'col_updated-at'],
                'contentOptions' => ['class' => 'col_updated-at'],
                'label' => Yii::t('app', 'Updated'),
                'format' => 'html',
                'filter' => \yii\jui\DatePicker::widget([
                    'model' => $searchModel,
                    'attribute' => 'updated_at',
                    'language' => 'lv',
                    'dateFormat' => 'yyyy-MM-dd',
                    'options' => ['class' => 'form-control']
                ]),
                'value' => function($searchModel) {

                    /**
                     * @var app\models\search\User $searchModel
                     */
                    return (!is_null($searchModel->updated_by) ?
                        User::usernameById($searchModel->updated_by) .
                            '<span class="col_updated-by__value">' .
                            $searchModel->formattedUpdatedAt .
                            '</span>' :
                        '-'
                    );
                },
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'headerOptions' => ['class' => 'col_actions'],
                'buttonOptions' => ['class' => 'btn btn-link btn-sm'],
                'template' => '<div class="btn-group" role="group">{view}{update}{delete}</div>'
            ],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

views/users/update.php
<?php

/**
 * Users update view
 *
 * @var yii\web\View $this
 * @var app\models\User $model
 */
?><div class="admin-page admin-page_data-update user-update">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/users/view.php
<?php

use app\models\User;
use yii\helpers\Html;
use yii\widgets\DetailView;

/**
 * Users view
 *
 * @var yii\web\View $this
 * @var app\models\User $model
 */
?><div class="admin-page admin-page_data-view user-view">
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'username',
            [
                'attribute' => 'status',
                'value' => $model->statusTitle
            ]
        ],
    ]) ?>
    <footer class="admin-data-view__footer row">
        <div class="col-md-9 entry-info">
        <?php if (!$model->isNewRecord): ?>
            <span class="entry__created"><?= Yii::t('app', 'Created') ?>: <span class="created-by"><?= User::usernameById($model->created_by) ?></span> (<span class="created-at"><?= $model->formattedCreatedAt ?></span>)</span>
            <?php if ($model->updated_at): ?>
            <span class="entry__updated"><?= Yii::t('app', 'Updated') ?>: <span class="updated-by"><?= User::usernameById($model->updated_by) ?></span> (<span class="updated-at"><?= $model->formattedUpdatedAt ?></span>)</span>
            <?php endif; ?>
        <?php endif; ?>
        </div>
        <div class="col-md-1">
            <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
                'class' => 'btn btn-block btn-link',
                'data' => [
                    'confirm' => Yii::t('app', 'Are you sure you want to delete this {modelClass}?', [
                        'modelClass' => Yii::t('app.models.User', 'User'),
                    ]),
                    'method' => 'post',
                ],
            ]) ?>
        </div>
        <div class="col-md-2">
            <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-block btn-primary']) ?>
        </div>
    </footer>
</div>